server {
    listen 80;
    server_name localhost;

    access_log /var/log/oncall-app/nginx_access.log;
    error_log  /var/log/oncall-app/nginx_error.log;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

#    location /admin/ {
#        root /usr/share/nginx/html;
#        index admin.html;
#        try_files $uri $uri/ /admin.html;
#    }

    location /api/ {
        proxy_pass http://oncall_app_3:8083;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin {
        proxy_pass http://oncall_app_3:8083;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
